#include "../lib/essentials.h"

Module T1 = {.id = 3,
			 .id_lookup = {-1, 0, 0, 3, 4, 4, 4, 4},
			 .dir_lookup = {OUT, OUT, OUT, OUT, LASER_LEFT, LASER_LEFT, LASER_LEFT, LASER_LEFT},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 3,
			 .nearest[STORAGE] = 4,
			 .is_storage = false,
			 .next = {4, -1, -1}};
Module T2 = {.id = 4,
			 .id_lookup = {-1, 0, 0, 3, 4, 7, 7, 7},
			 .dir_lookup = {OUT, OUT, OUT, LASER_RIGHT, OUT, LASER_LEFT, LASER_LEFT, LASER_LEFT},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 3,
			 .nearest[STORAGE] = 7,
			 .is_storage = true,
			 .to_storage = RFID,
			 .next = {5, 3, 7}};
Module T3 = {.id = 5,
			 .id_lookup = {-1, 0, 0, 4, 4, 5, 4, 4},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .dir_lookup = {OUT, OUT, OUT, LASER_LEFT, LASER_LEFT, OUT, LASER_LEFT, LASER_LEFT},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 3,
			 .nearest[STORAGE] = 4,
			 .is_storage = true,
			 .to_storage = RFID,
			 .next = {6, -1, 4}};
Module T4 = {.id = 6,
			 .id_lookup = {-1, 0, 0, 5, 5, 5, 6, 5},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .dir_lookup = {OUT, OUT, OUT, LASER_LEFT, LASER_LEFT, LASER_LEFT, OUT, LASER_LEFT},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 3,
			 .nearest[STORAGE] = 5,
			 .is_storage = true,
			 .to_storage = RFID,
			 .next = {7, -1, 5}
			};
Module T5 = {.id = 7,
			 .id_lookup = {-1, 0, 0, 6, 6, 6, 6, 7},
			 .dir_lookup = {OUT, OUT, OUT, LASER_LEFT, LASER_LEFT, LASER_LEFT, LASER_LEFT, OUT},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 3,
			 .nearest[STORAGE] = 6,
			 .is_storage = true,
			 .to_storage = RFID,
			 .next = {4, -1, 6}};

// Unused for now
Module T6 = {.id = 8,
			 .id_lookup = {1, 2, 3},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 4,
			 .is_storage = true,
			 .to_storage = RFID,
			 .next = {1, 2, 3}};
Module T7 = {.id = 9,
			 .id_lookup = {1, 2, 3},
			 //.plane_to_id = {-1, -1, -1, -1},
			 .nearest[DROPOFF] = -1,
			 .nearest[QUARANTINE] = -1,
			 .nearest[SECURITY] = 7,
			 .nearest[PLANE] = 4,
			 .to_storage = RFID,
			 .is_storage = true,
			 .next = {1, 2, 3}};
